version: '3.8'

services:
  exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"

  telegraf:
    image: telegraf:1.19.2
    ports:
      - "9273:9273"
    volumes:
      - ./docker/telegraf.conf:/etc/telegraf/telegraf.conf

  opentsdb:
    image: petergrace/opentsdb-docker
    ports:
      - "4243:4242"

  grafana:
    image: grafana/grafana
    depends_on:
      - opentsdb
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/

  tcollector:
    build:
      context: ./docker/tcollector
      dockerfile: Containerfile
    image: tcollector:dev
    command: -H collector -p 4242 --http

  collector:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: otel-collector:dev
    ports:
      - "4242:4242"
    volumes:
      - ./config/otelcol-docker.yaml:/config/otelcol.yaml
