receivers:
  prometheus_simple:
    collection_interval: 10s
    endpoint: "localhost:9273"

  opentsdb:
    endpoint: 0.0.0.0:4242

exporters:
  opentsdb:
    endpoint: http://localhost:4242/api/put
    batch_size: 25
    skip_tags:
      - scheme
      - port
      - service.name
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers:
        - opentsdb
      exporters:
        - logging
  telemetry:
    logs:
      level: "debug"
