dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.89.0
receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver v0.89.0"
  - gomod: "github.com/foxlegend/opentelemetry-collector-opentsdb-contrib/receiver/opentsdbreceiver v0.89.0"
    path: "./receiver/opentsdbreceiver"
exporters:
  - gomod: "github.com/foxlegend/opentelemetry-collector-opentsdb-contrib/exporter/opentsdbexporter v0.89.0"
    path: "./exporter/opentsdbexporter"
  - import: "go.opentelemetry.io/collector/exporter/loggingexporter"
    gomod: "go.opentelemetry.io/collector v0.89.0"
  - gomod:  "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.89.0"
