receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver v0.51.0"
  - gomod: "github.com/foxlegend/opentelemetry-collector-opentsdb-contrib/receiver/opentsdbreceiver v0.51.0"
    path: "./receiver/opentsdbreceiver"
exporters:
  - gomod: "github.com/foxlegend/opentelemetry-collector-opentsdb-contrib/exporter/opentsdbexporter v0.51.0"
    path: "./exporter/opentsdbexporter"
  - import: "go.opentelemetry.io/collector/exporter/loggingexporter"
    gomod: "go.opentelemetry.io/collector v0.51.0"
  - gomod:  "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.51.0"
